### PR TITLE
Folders for game modes

### PR DESCRIPTION
**Pull request by Jack-Papel**

### CODE REVIEW

**Review by ItsSammyM — CHANGES_REQUESTED** [review]
You changed the format for how gamemodes are saved. 
If i try to copy and paste a gamemode it doesnt work now.
Its missing a name or something.

**Review by ItsSammyM — CHANGES_REQUESTED** [review]
Why is the version of the game saved in the default game mode folder? I don't care to save the version of the default game modes, Just the version of the game.
If the local storage changes at all, not just game modes, then it could be corrupt. Version could even get its own file.

The only way to get the default game modes is by erasing save data. I would rather not, but fine.

When you import a game mode into an actual lobby. It only adds up to the correct amount of role outlines. That is good. When you hit the copy button, it should only copy that number of outlines. If you don't fix this, make an issue for it before merging.
Currently, it copies the entire gamemode, even though thats not what you are currently seeing in the game mode settings.

**Comment by Jack-Papel** [comment]
Bro did not read closely. I'll explain in person tomorrow.
The `format` field is more like a schema. It's not a version of the default game modes, it's the schema for the format of how game modes are saved

**Comment by Jack-Papel** [comment]
We talked about this in-person. Re-requesting review

**Review by ItsSammyM — APPROVED** [review]

**Pull request merged**
