### PR TITLE
Button element + overhaul menus: main, lobby, game mode editor

### LINKED ISSUE #503: Excluded roles selector
New UI

It should look like encyclopedia. A list of all the roles, when you click on a role name, it becomes gray.
Above that interface, is a role outline selector, the two of them will be in sync, so you can use either menu. That way people who know what is going on can select town killing to disable all the town killing roles, but someone who doesn't can just click on each of the town killing roles.

Rename to disabled roles

### PR DESCRIPTION
**Pull request by Jack-Papel**
Closes #503

### CODE REVIEW

**Review by ItsSammyM — CHANGES_REQUESTED** [review]
Screenshot 2024-04-15 022618

The X button on the game screen content menu looks wrong. The question mark also does. The icons are not centered.

The disabled roles display in game (shown in screenshot) is miserable, you should try to find a way to use the DisabledRoleSelector here. Or do something else to display this well.

Maybe you should take PhaseTimeSelector DisabledRoleSelector GameModesSelector etc into a different folder other than components since there is so many of these now.

In the settings menu, erase save data should be on the bottom. It should be the last option. The settings menu should also show what the name of the lobby you are in is.

I did look through the code and I think everything I understood is fine. I actually don't understand half of Button.tsx because i don't know what a memo is.

If you think any of this does not belong in this PR. please make an issue for it.

**Comment by Frogz9000** [comment]
lgtmbbgily get nasty with it

**Comment by Jack-Papel** [comment]
Making a todo list so I remember everything:
- [ ] Centered 'X' and '?' icons on GameScreen
- [ ] Improved disabled roles display
- [x] Move selectors into new folder (Made issue #609, will address after this PR is merged to avoid conflicts)
- [ ] Erase save data at bottom of settings menu
- [ ] Lobby name in settings menu

**Review by ItsSammyM — CHANGES_REQUESTED** [review]
LobbyName is not sent to players who join late, or at least not shown in the settings menu

Lobbies are not appearing in the server browser

If you dont want this PR to get too bloated do not do this, or if you see an issue with having two hosts do not do this - Add a make host button in the player list on the lobby screen next to the kick button.

**Review by ItsSammyM — APPROVED** [review]

**Pull request merged**
